---
title: "Prepare_base_data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Prepare_base_data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
#| eval: false
library(PEMr)
```


## 2. Generating base data for modelling (5m resolution as default) 


```{r setup}

#| eval: false
library(PEMr)
library(PEMprepr)

#project_name <- "{{ aoi_name }}"
#project_name <- "datecreek_aoi"

fid <- read_fid()

```


### create model templates 

```{r create template}
#| eval: false
aoi_dir = read_fid()$dir_0010_vector$path_abs
files <- list.files(aoi_dir, pattern = "([.]gpkg)|([.]shp)$")
aoi_file = fs::path(aoi_dir, files )


# vector
aoi <- snap_aoi(aoi_file, method = "expand")

aoi <- fs::path(PEMprepr::read_fid()$dir_1010_vector$path_abs, "aoi_snapped.gpkg")

# raster

# Prepare Raster Data(for 5m lidar template)

r5 <- create_template_raster(aoi, res = 5)

```


### generate base vector layers

```{r}
#| eval: false
create_base_vectors(aoi, out_dir = PEMprepr::read_fid()$dir_1010_vector$path_abs)

```


### generate base DEM layer for modelling (5m)

```{r}
#| eval: false
#1) option to use trim data 

dem = get_cded_dem(aoi = fs::path(PEMprepr::read_fid()$dir_1020_covariates$path_abs, "25m", "template.tif"),
                   res = 5,
                   overwrite = TRUE)

#2) option to use lidr 

```

### generate raster covariates for modelling (5m)


```{r}
#| eval: false
# get model covariates 

find_saga_path()

saga_cmd()


create_covariates(
   dtm = fs::path(PEMprepr::read_fid()$dir_1020_covariates$path_rel,"5m","dem.tif"),
   saga_path = saga_cmd(),
   out_dir = PEMprepr::read_fid()$dir_1020_covariates$path_rel,
   layers = "all"
)


```


### Create a bec raster to match the template sizes 

```{r}
#| eval: false
# generate a 5m raster
bec_rast5 <- create_bgc_template(
  field = "MAP_LABEL",
  template =  r5,
  write_output = FALSE
)

```


congratulations you are now ready to start developing the sample plan


